language: java
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - jasig-cas-3.5.3-update
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
script: mvn clean install deploy
env:
  global:
  - secure: L0VnheAQ1MH8Do4krbx49Dt/mbfHaz8mVv8c4LgvkurAoNtnrmk2N68q/BP5cDpyUl9MUt7APtzzl6xCmAAX/yTYL3r8vJhWbY76/pv1UN5OOWVXn5TIhJRFu/7GULj/hHLNzC3AM3Pf1glWZ2CBA9dElsc38J+GGt6iCZSSC6I=
  - secure: ePPqUnaq1DCRh4gDQDSKlaWZU91aH2KixACfZgfesGftfPFeSa7FauBxbvKAkZWp/YkSKeY/gHiPLZQqX0y/nxZ90lrZ1xDxFnzLTKeEIZZ2OGJJDzmTrnhV3ueFllAP0eIlb29cLis5FlV74xaSvparK/R+EhfQ6mjPQRWxbmI=
